spring.application.name=email_fetcher
spring.datasource.url=jdbc:postgresql://db.iaopckrbwbbtgmtptbux.supabase.co:5432/postgres
spring.datasource.username=postgres.iaopckrbwbbtgmtptbux
spring.datasource.password=1Uy2ALYt8n0i5Ukb